# Generated by Django 4.2 on 2023-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_client_id', models.CharField(max_length=100)),
                ('spotify_client_secret', models.CharField(max_length=100)),
                ('spotify_callback_url', models.CharField(max_length=100)),
                ('linux_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
