# Generated by Django 4.2 on 2023-04-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_uid', models.CharField(max_length=200)),
                ('card_uid', models.CharField(max_length=200)),
            ],
        ),
    ]
