# Generated by Django 4.2 on 2023-04-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_musiccard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='linux_mode',
        ),
    ]
