# Generated by Django 4.2 on 2023-04-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_configuration_linux_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccard',
            name='music_type',
            field=models.CharField(choices=[('al', 'Album'), ('tr', 'Track'), ('pl', 'Playlist')], default='tr', max_length=2),
        ),
    ]
