# Generated by Django 4.2 on 2023-05-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_configuration_spotify_speaker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='musiccard',
            name='spotify_cover',
            field=models.ImageField(blank=True, upload_to='cover_art/'),
        ),
        migrations.AddField(
            model_name='musiccard',
            name='spotify_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='musiccard',
            name='spotify_track_num',
            field=models.IntegerField(default=0),
        ),
    ]
