# Generated by Django 4.2 on 2023-05-07 22:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_musiccard_last_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiccard',
            name='spotify_cover',
        ),
        migrations.AddField(
            model_name='musiccard',
            name='spotify_cover_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='musiccard',
            name='music_type',
            field=models.CharField(choices=[(app.models.CardChoices['AL'], 'Album'), (app.models.CardChoices['PL'], 'Playlist'), (app.models.CardChoices['TR'], 'Track')], default='TR', max_length=2),
        ),
    ]
