# Generated by Django 4.2 on 2023-05-07 22:04

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_musiccard_last_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiccard',
            name='spotify_cover',
        ),
        migrations.AddField(
            model_name='musiccard',
            name='spotify_cover_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
