# Generated by Django 4.2 on 2023-05-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_musiccard_music_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musiccard',
            name='music_type',
        ),
        migrations.AddField(
            model_name='musiccard',
            name='spotify_music_type',
            field=models.CharField(choices=[('AL', 'Album'), ('PL', 'Playlist'), ('TR', 'Track')], default='TR', max_length=2),
        ),
    ]
