# Generated by Django 4.2 on 2023-08-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_configuration_current_card_uid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='reader_type',
            field=models.CharField(choices=[('NEUF', 'Neuftech'), ('MFRC', 'MFRC 522')], default='NEUF', max_length=4),
        ),
    ]
