# Generated by Django 4.2 on 2023-08-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_configuration_reader_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='jukebox_volume',
            field=models.FloatField(default=0.5),
        ),
    ]
