# Generated by Django 4.2 on 2023-08-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_configuration_jukebox_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='jukebox_spotify_type',
            field=models.CharField(choices=[('PSST', 'Psst Client'), ('WEB', 'Spotify Web API')], default='WEB', max_length=4),
        ),
    ]
